import React, { useCallback, useEffect, useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, RefreshControl } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import SearchBar from '../../components/SearchBar';
import MedicineCard from '../../components/MedicineCard';
import PharmacyCard from '../../components/PharmacyCard';
import { ErrorState, LoadingSkeleton, EmptyState } from '../../components/ScreenState';
import { useAuth } from '../../context/AuthContext';
import { getPharmacies, getMedicines, addFavorite } from '../../services/api';
import { colors, radius, shadows, spacing, typography } from '../../theme';

const shortcuts=[{label:'Pesquisar',icon:'search-outline',screen:'Pesquisar'},{label:'Favoritos',icon:'heart-outline',screen:'Favoritos'},{label:'Perfil',icon:'person-outline',screen:'Perfil'}];
export default function HomeScreen({ navigation }) {
  const { user }=useAuth(); const[medicines,setMedicines]=useState([]); const[pharmacies,setPharmacies]=useState([]); const[loading,setLoading]=useState(true); const[refreshing,setRefreshing]=useState(false); const[error,setError]=useState('');
  const load=useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);setError('');try{const[medRes,phRes]=await Promise.all([getMedicines(),getPharmacies()]);setMedicines((medRes.data||[]).slice(0,4));setPharmacies((phRes.data||[]).slice(0,3));}catch(e){setError(e.response?'Não foi possível carregar as informações.':'Sem ligação à Internet. Verifique a rede e tente novamente.')}finally{setLoading(false);setRefreshing(false)}},[]);
  useEffect(()=>{load()},[load]);
  const save=async id=>{try{await addFavorite(id)}catch(e){if(e.response?.status!==400)setError('Não foi possível guardar o medicamento.')}};
  return <ScrollView style={styles.container} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor={colors.primary}/> }>
    <View style={styles.welcome}><View style={{flex:1}}><Text style={styles.greeting}>Olá, {String(user?.name||'utilizador').split(' ')[0]}</Text><Text style={styles.prompt}>Como podemos ajudar hoje?</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>{String(user?.name||'FB').slice(0,2).toUpperCase()}</Text></View></View>
    <TouchableOpacity activeOpacity={.9} onPress={()=>navigation.navigate('Pesquisar')}><View pointerEvents="none"><SearchBar placeholder="Pesquisar medicamento..." /></View></TouchableOpacity>
    <View style={styles.shortcuts}>{shortcuts.map(x=><TouchableOpacity key={x.label} style={styles.shortcut} onPress={()=>navigation.navigate(x.screen)}><View style={styles.shortcutIcon}><Ionicons name={x.icon} size={22} color={colors.primary}/></View><Text style={styles.shortcutText}>{x.label}</Text></TouchableOpacity>)}</View>
    <View style={styles.notice}><Ionicons name="information-circle-outline" size={23} color={colors.support}/><Text style={styles.noticeText}>Consulte um profissional de saúde antes de utilizar qualquer medicamento.</Text></View>
    {error&&!medicines.length&&!pharmacies.length?<ErrorState message={error} onRetry={load}/>:<>{loading?<LoadingSkeleton rows={4}/>:<><Section title="Medicamentos disponíveis" action="Ver todos" onPress={()=>navigation.navigate('Pesquisar')}/>{medicines.length?medicines.map(item=><MedicineCard key={item.id} item={item} onFavorite={()=>save(item.id)} onPress={()=>navigation.navigate('MedicineDetails',{item})}/>):<EmptyState title="Nenhum medicamento disponível" message="Volte a tentar mais tarde."/>}<Section title="Farmácias disponíveis"/>{pharmacies.length?pharmacies.map(item=><PharmacyCard key={item.id} item={item} onPress={()=>navigation.navigate('PharmacyDetails',{item})}/>):<EmptyState title="Nenhuma farmácia disponível" message="As farmácias aprovadas aparecerão aqui."/>}</>}</>}
  </ScrollView>;
}
function Section({title,action,onPress}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{action?<TouchableOpacity onPress={onPress}><Text style={styles.sectionAction}>{action}</Text></TouchableOpacity>:null}</View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:spacing.xl,paddingBottom:40},welcome:{flexDirection:'row',alignItems:'center',marginBottom:18},greeting:{...typography.caption,color:colors.primaryDark,fontWeight:'700'},prompt:{...typography.title,color:colors.text,marginTop:3},avatar:{width:48,height:48,borderRadius:24,backgroundColor:colors.primaryLight,alignItems:'center',justifyContent:'center'},avatarText:{color:colors.primaryDark,fontWeight:'800'},shortcuts:{flexDirection:'row',gap:10,marginVertical:18},shortcut:{flex:1,alignItems:'center',backgroundColor:colors.surface,paddingVertical:14,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,...shadows.card},shortcutIcon:{width:42,height:42,borderRadius:14,backgroundColor:colors.primaryLight,alignItems:'center',justifyContent:'center'},shortcutText:{fontSize:12,color:colors.text,fontWeight:'700',marginTop:7},notice:{flexDirection:'row',gap:10,backgroundColor:'#EFF6FF',borderRadius:radius.md,padding:14,marginBottom:10},noticeText:{...typography.caption,color:'#1E3A8A',flex:1},section:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:20,marginBottom:10},sectionTitle:{...typography.heading,color:colors.text},sectionAction:{color:colors.primary,fontWeight:'700',fontSize:13}});
