import React,{useState} from 'react';
import {View,Text,StyleSheet,TouchableOpacity,Alert,ScrollView,Image,Platform} from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import {Ionicons} from '@expo/vector-icons';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useAuth} from '../../context/AuthContext';
import {updatePharmacyProfile} from '../../services/api';
import CustomButton from '../../components/CustomButton';
import {colors,radius,spacing,typography} from '../../theme';

const documentTypes={nuit:{title:'Comprovativo do NUIT',description:'Documento oficial onde consta o NUIT da farmácia.'},license:{title:'Licença ou alvará',description:'Documento que comprova que a farmácia está autorizada a funcionar.'}};
const getUploadPart=async(file,name,type)=>{if(Platform.OS!=='web')return{uri:file.uri,name,type:file.mimeType||type};if(file.file)return file.file;const response=await fetch(file.uri);const blob=await response.blob();return new File([blob],name,{type:blob.type||file.mimeType||type})};
export default function PharmacyProfileDocs({navigation}){const[files,setFiles]=useState({nuit:null,license:null});const[photos,setPhotos]=useState([]);const[submitting,setSubmitting]=useState(false);const{logout}=useAuth();
 const goBackToData=()=>navigation.canGoBack()?navigation.goBack():navigation.navigate('PharmacyProfileSetup');
 const cancel=()=>Alert.alert('Cancelar envio?','Os documentos selecionados não serão enviados. Pode continuar o cadastro mais tarde.',[{text:'Continuar aqui',style:'cancel'},{text:'Cancelar',style:'destructive',onPress:()=>logout('Login')}]);
 const pickDocument=async key=>{try{const result=await DocumentPicker.getDocumentAsync({type:['application/pdf','image/*'],copyToCacheDirectory:true,multiple:false});if(result.canceled)return;const asset=result.assets?.[0];if(asset)setFiles(old=>({...old,[key]:asset}));}catch(e){Alert.alert('Erro','Não foi possível selecionar o documento.')}};
 const pickPhotos=async()=>{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return Alert.alert('Permissão necessária','Autorize o acesso às fotografias para anexar os documentos.');const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,quality:.8,selectionLimit:6});if(!result.canceled)setPhotos(old=>[...old,...result.assets].slice(0,6));};
 const removePhoto=index=>setPhotos(old=>old.filter((_,i)=>i!==index));
 const submit=async()=>{if(!files.nuit||!files.license)return Alert.alert('Documentos em falta','Adicione o comprovativo do NUIT e a licença ou alvará.');if(!photos.length)return Alert.alert('Foto em falta','Adicione uma foto do estabelecimento.');if(submitting)return;setSubmitting(true);try{const form=new FormData();for(const[prefix,file]of[['nuit',files.nuit],['licenca',files.license]])form.append('documents',await getUploadPart(file,`${prefix}-${file.name||'documento'}`,'application/octet-stream'));for(let i=0;i<photos.length;i++)form.append('documents',await getUploadPart(photos[i],`estabelecimento-${i+1}.jpg`,'image/jpeg'));const updated=await updatePharmacyProfile(form);const uploaded=Array.isArray(updated?.documents)?updated.documents.filter(document=>document?.url):[];if(uploaded.length<3)throw new Error('UPLOAD_INCOMPLETE');Alert.alert('Documentos enviados','O cadastro foi enviado para análise. Pode acompanhar o estado no Painel.',[{text:'Ir ao Painel',onPress:()=>navigation.replace('PharmacyTabs')}]);}catch(e){const message=e.message==='UPLOAD_INCOMPLETE'?'O servidor não guardou todos os ficheiros. Tente enviar novamente.':e.code==='ECONNABORTED'?'O envio demorou demasiado. Verifique a ligação e tente novamente.':e.response?'Não foi possível enviar os documentos. Tente novamente.':'Não foi possível contactar o servidor. Verifique a ligação.';Alert.alert('Falha no envio',message)}finally{setSubmitting(false)}};
 return <SafeAreaView style={styles.safe}><ScrollView style={styles.page} contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator nestedScrollEnabled persistentScrollbar><Progress/><Text style={styles.title}>Documentos da farmácia</Text><Text style={styles.subtitle}>Envie ficheiros legíveis. PDF, JPG ou PNG são aceites.</Text>{Object.entries(documentTypes).map(([key,info])=><DocumentField key={key} info={info} file={files[key]} onPick={()=>pickDocument(key)} onRemove={()=>setFiles(old=>({...old,[key]:null}))}/>)}<View style={styles.section}><View style={styles.sectionHeader}><View style={styles.icon}><Ionicons name="camera-outline" size={21} color={colors.primaryDark}/></View><View style={{flex:1}}><Text style={styles.sectionTitle}>Foto do estabelecimento</Text><Text style={styles.sectionText}>Adicione uma foto que permita identificar claramente a farmácia.</Text></View></View><TouchableOpacity style={styles.outlineButton} onPress={pickPhotos}><Ionicons name="camera-outline" size={19} color={colors.primary}/><Text style={styles.outlineText}>Adicionar foto do estabelecimento</Text></TouchableOpacity>{photos.length?<View style={styles.photos}>{photos.map((photo,i)=><View key={`${photo.uri}-${i}`} style={styles.photoWrap}><Image source={{uri:photo.uri}} style={styles.photo}/><TouchableOpacity style={styles.removePhoto} onPress={()=>removePhoto(i)}><Ionicons name="close" size={16} color={colors.surface}/></TouchableOpacity></View>)}</View>:null}</View><View style={styles.notice}><Ionicons name="lock-closed-outline" size={19} color={colors.support}/><Text style={styles.noticeText}>Os documentos são privados e usados apenas pela administração para verificar a farmácia.</Text></View><CustomButton title="Enviar para análise" icon="cloud-upload-outline" loading={submitting} disabled={submitting||!files.nuit||!files.license||!photos.length} onPress={submit}/><CustomButton title="Voltar e corrigir dados" variant="secondary" disabled={submitting} onPress={goBackToData}/><CustomButton title="Cancelar" variant="secondary" disabled={submitting} onPress={cancel}/></ScrollView></SafeAreaView>}
function Progress(){return <View style={styles.progress}><View style={styles.progressTrack}><View style={styles.progressFill}/></View><Text style={styles.progressText}>Etapa 2 de 2</Text></View>}
function DocumentField({info,file,onPick,onRemove}){return <View style={styles.section}><View style={styles.sectionHeader}><View style={styles.icon}><Ionicons name="document-text-outline" size={21} color={colors.primaryDark}/></View><View style={{flex:1}}><Text style={styles.sectionTitle}>{info.title}</Text><Text style={styles.sectionText}>{info.description}</Text></View></View>{file?<View style={styles.file}><Ionicons name="checkmark-circle" size={22} color={colors.primary}/><Text style={styles.fileName} numberOfLines={1}>{file.name}</Text><TouchableOpacity onPress={onRemove} hitSlop={8}><Ionicons name="trash-outline" size={20} color={colors.error}/></TouchableOpacity></View>:<TouchableOpacity style={styles.outlineButton} onPress={onPick}><Ionicons name="attach-outline" size={20} color={colors.primary}/><Text style={styles.outlineText}>Selecionar documento</Text></TouchableOpacity>}</View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},page:{flex:1,backgroundColor:colors.background},container:{flexGrow:1,padding:spacing.xl,paddingBottom:64},progress:{marginBottom:20},progressTrack:{height:6,borderRadius:3,backgroundColor:colors.border},progressFill:{height:6,width:'100%',borderRadius:3,backgroundColor:colors.primary},progressText:{...typography.caption,color:colors.primaryDark,fontWeight:'700',marginTop:7},title:{...typography.title,color:colors.text},subtitle:{...typography.body,color:colors.textSecondary,marginTop:5,marginBottom:18},section:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:16,marginBottom:12},sectionHeader:{flexDirection:'row',gap:12},icon:{width:42,height:42,borderRadius:12,backgroundColor:colors.primaryLight,alignItems:'center',justifyContent:'center'},sectionTitle:{...typography.heading,color:colors.text,fontSize:16},sectionText:{...typography.caption,color:colors.textSecondary,marginTop:3},outlineButton:{minHeight:48,borderRadius:radius.md,borderWidth:1,borderStyle:'dashed',borderColor:colors.primary,marginTop:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},outlineText:{color:colors.primaryDark,fontWeight:'700'},file:{flexDirection:'row',alignItems:'center',gap:9,backgroundColor:colors.primaryMuted,padding:12,borderRadius:radius.md,marginTop:14},fileName:{flex:1,color:colors.text,fontWeight:'600'},photos:{flexDirection:'row',flexWrap:'wrap',gap:9,marginTop:14},photoWrap:{width:82,height:82},photo:{width:82,height:82,borderRadius:radius.md},removePhoto:{position:'absolute',right:-5,top:-5,width:24,height:24,borderRadius:12,backgroundColor:colors.error,alignItems:'center',justifyContent:'center'},notice:{flexDirection:'row',gap:9,backgroundColor:'#EFF6FF',padding:13,borderRadius:radius.md},noticeText:{...typography.caption,color:'#1E3A8A',flex:1}});
