import React,{useState} from 'react';
import {Alert,KeyboardAvoidingView as NativeKeyboardAvoidingView,Modal,Platform,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Controller,useForm} from 'react-hook-form';
import {Ionicons} from '@expo/vector-icons';
import {useAuth} from '../../context/AuthContext';
import CustomInput from '../../components/CustomInput';
import CustomButton from '../../components/CustomButton';
import {createPharmacyProfile} from '../../services/api';
import {colors,radius,spacing,typography} from '../../theme';

const districtsByProvince={
 Maputo:['Maputo Cidade','Matola','Boane','Marracuene','Magude'],Gaza:['Xai-Xai','Chibuto','Massingir','Bilene','Mabalane'],Inhambane:['Inhambane','Maxixe','Vilankulo','Jangamo','Panda'],Sofala:['Beira','Dondo','Nhamatanda','Muanza','Save'],Manica:['Chimoio','Barue','Gondola','Sussundenga','Machaze'],Tete:['Tete','Moatize','Mutarara','Chiuta','Angónia'],'Zambézia':['Quelimane','Milange','Gurué','Alto Molócuè','Namacurra'],Nampula:['Nampula','Malema','Mecubúri','Ribaue','Monapo'],Niassa:['Lichinga','Cuamba','Majune','Sanga','Marrupa'],'Cabo Delgado':['Pemba','Metuge','Mueda','Montepuez','Ancuabe']
};

function KeyboardAvoidingView({children,style,behavior}){
 if(Platform.OS==='web')return <View style={style}>{children}</View>;
 return <NativeKeyboardAvoidingView style={style} behavior={behavior}>{children}</NativeKeyboardAvoidingView>;
}

export default function PharmacyProfileSetup({navigation}){
 const[loading,setLoading]=useState(false),[picker,setPicker]=useState(null);const{logout}=useAuth();
 const{control,handleSubmit,setValue,watch,formState:{errors}}=useForm({defaultValues:{name:'',nuit:'',address:'',province:'',district:'',openingHours:''}});
 const province=watch('province'),districts=districtsByProvince[province]||[];
 const goBack=async()=>navigation.canGoBack()?navigation.goBack():logout('Register');
 const submit=async data=>{if(loading)return;setLoading(true);try{await createPharmacyProfile(data);navigation.navigate('PharmacyProfileDocs')}catch(e){Alert.alert('Não foi possível continuar','Verifique os dados e a ligação ao servidor.')}finally{setLoading(false)}};
 const field=(name,label,placeholder,rules={},props={})=><Controller control={control} name={name} rules={rules} render={({field:{onChange,value}})=><CustomInput label={label} placeholder={placeholder} value={value} onChangeText={onChange} error={errors[name]?.message}{...props}/>}/>;
 const select=(name,label,placeholder,disabled=false)=><Controller control={control} name={name} rules={{required:`Selecione ${name==='province'?'a província':'o distrito'}`}} render={({field:{value}})=><View style={styles.selectField}><Text style={styles.label}>{label}</Text><TouchableOpacity style={[styles.selectBox,disabled&&styles.disabled,errors[name]&&styles.invalid]} disabled={disabled} onPress={()=>setPicker(name)}><Text style={[styles.selectValue,!value&&styles.placeholder]}>{value||placeholder}</Text><Ionicons name="chevron-down" size={19} color={colors.textSecondary}/></TouchableOpacity>{errors[name]?<Text style={styles.error}>{errors[name].message}</Text>:null}</View>}/>;
 const options=picker==='province'?Object.keys(districtsByProvince):districts;
 return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.page} behavior={Platform.OS==='ios'?'padding':'height'}><ScrollView style={styles.page} contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" showsVerticalScrollIndicator nestedScrollEnabled persistentScrollbar><Progress/><Text style={styles.title}>Dados da farmácia</Text><Text style={styles.subtitle}>Informe os dados legais e a localização. Na etapa seguinte serão pedidos os documentos.</Text>{field('name','Nome da farmácia','Nome comercial',{required:'Informe o nome'},{icon:'storefront-outline'})}{field('nuit','NUIT','9 dígitos',{required:'Informe o NUIT',pattern:{value:/^\d{9}$/,message:'O NUIT deve ter exatamente 9 dígitos'}},{icon:'document-text-outline',keyboardType:'number-pad',maxLength:9})}{field('address','Endereço','Ex.: Av. 25 de Setembro, nº 123',{required:'Informe o endereço'},{icon:'location-outline'})}{select('province','Província','Selecione a província')}{select('district','Distrito',province?'Selecione o distrito':'Selecione primeiro a província',!province)}{field('openingHours','Horário de funcionamento','08:00 - 20:00',{required:'Informe o horário'},{icon:'time-outline'})}<CustomButton title="Continuar para documentos" icon="arrow-forward" loading={loading} disabled={loading} onPress={handleSubmit(submit)}/><CustomButton title="Voltar" variant="secondary" disabled={loading} onPress={goBack}/></ScrollView></KeyboardAvoidingView><Modal visible={Boolean(picker)} transparent animationType="fade" onRequestClose={()=>setPicker(null)}><TouchableOpacity style={styles.overlay} activeOpacity={1} onPress={()=>setPicker(null)}><View style={styles.modal} onStartShouldSetResponder={()=>true}><Text style={styles.modalTitle}>Selecione {picker==='province'?'a província':'o distrito'}</Text><ScrollView style={styles.options} nestedScrollEnabled>{options.map(item=><TouchableOpacity key={item} style={styles.option} onPress={()=>{setValue(picker,item,{shouldValidate:true});if(picker==='province')setValue('district','');setPicker(null)}}><Text style={styles.optionText}>{item}</Text></TouchableOpacity>)}</ScrollView></View></TouchableOpacity></Modal></SafeAreaView>
}
function Progress(){return <><Text style={styles.progressText}>Etapa 1 de 2</Text><Text style={styles.progressBar}>━━━━━━━━━━<Text style={styles.progressRest}>━━━━━━━━━━</Text></Text></>}
const styles=StyleSheet.create({safe:{flex:1,minHeight:0,backgroundColor:colors.background},page:{flex:1,minHeight:0,overflow:'scroll',backgroundColor:colors.background},container:{flexGrow:1,padding:spacing.xl,paddingBottom:96},progressText:{...typography.caption,color:colors.primaryDark,fontWeight:'700'},progressBar:{color:colors.primary,fontSize:16,marginBottom:14},progressRest:{color:colors.border},title:{...typography.title,color:colors.text},subtitle:{...typography.body,color:colors.textSecondary,marginTop:5,marginBottom:20},selectField:{marginBottom:16},label:{...typography.body,color:colors.text,fontWeight:'600',marginBottom:7},selectBox:{minHeight:56,flexDirection:'row',alignItems:'center',paddingHorizontal:16,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface},selectValue:{...typography.body,color:colors.text,flex:1},placeholder:{color:colors.textSecondary},disabled:{opacity:.55},invalid:{borderColor:colors.error},error:{...typography.caption,color:colors.error,marginTop:5},overlay:{flex:1,backgroundColor:'rgba(15,23,42,.4)',justifyContent:'center',padding:20},modal:{backgroundColor:colors.surface,borderRadius:radius.lg,padding:18,maxHeight:440},modalTitle:{...typography.heading,color:colors.text,fontSize:18,marginBottom:10},options:{maxHeight:340},option:{paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.border},optionText:{...typography.body,color:colors.text,fontWeight:'600'}});
